version: '3'

services:
    api:
        build: ./api
        container_name: api
        restart: always
        expose:
            - 8000
        networks:
            - api_network
            - nginx_network
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - api_volume:/api
    postgres:
        image: postgres:alpine
        container_name : postgres
        restart : always
        expose:
            - 5432
        networks:
            - api_network
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres_volume:/var/lib/postgresql/data
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        networks:
            - nginx_network
        depends_on:
            - api
        volumes:
            - nginx_volume:/etc/nginx/conf.d
            - static_volume:/api/static/

volumes:
    api_volume:
        external: true
    static_volume:
        external: true
    nginx_volume:
        external: true
    postgres_volume:
        external: true
networks:
    api_network:
        external: true
    nginx_network:
        external: true
    