# Generated by Django 4.1 on 2022-08-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('about', models.CharField(max_length=500, verbose_name='درباره')),
                ('body', models.TextField(verbose_name='توضیحات مستند')),
                ('type', models.CharField(choices=[('li', 'کتابخانه'), ('fr', 'فریمورک')], default='li', max_length=10, verbose_name='نوع')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'مستند ها',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='نام فارسی')),
                ('about', models.CharField(max_length=500, verbose_name='درباره')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان ها',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.document', verbose_name='داکیومنت')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحه ها',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.language', verbose_name='زبان'),
        ),
    ]
